version: "3.8"

services:
  elementor-nestjs:
    build: ./services/nestjs
    restart: always
    depends_on:
      - elementor-mysql

  elementor-react:
    build: ./services/react
    restart: always
    environment:
      - PORT=80

  elementor-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  elementor-nginx:
    image: nginx
    restart: always
    ports:
      - "8084:8084"
    volumes:
      - ./services/nginx/cfg/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - elementor-react
      - elementor-nestjs
      - elementor-mysql

volumes:
  db-data:
