version: '3.8'

services:
  elementor-nestjs:
    restart: always
    build:
      context: ./services/nestjs
      dockerfile: dev.Dockerfile
    depends_on:
      - elementor-mysql
    volumes:
      - ./services/nestjs/src/src:/app/src

  elementor-react:
    restart: always
    build:
      context: ./services/react
      dockerfile: dev.Dockerfile
    environment:
      - PORT=80
    volumes:
      - ./services/react/src/src:/app/src

  elementor-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  elementor-nginx:
    image: nginx
    restart: always
    ports:
      - '8084:8084'
    volumes:
      - ./services/nginx/cfg/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - elementor-react
      - elementor-nestjs
      - elementor-mysql

volumes:
  db-data: